<?php
echo "
<div class='navbar'>
    <div class='logo-container'>
        <img src='images/logo.png' class='Logo' style='width: 50%; height: auto;'>
    </div>
    <ul class='nav-items'>
        <li><a href='index.php' class='nav-link'>Home</a></li>
        <li><a href='jobs.php' class='nav-link'>Jobs</a></li>
        <li><a href='apply.php' class='nav-link'>Apply</a></li>
        <li><a href='about.php' class='nav-link'>About</a></li>
        <li><a href='enhancements.php' class='nav-link'>Enhancements</a></li>
        <li><a href='enhancements2.php' class='nav-link'>Enhancements-2</a></li>
	<li><a href='login.php' class='nav-link'>Login</a></li>
    </ul>
</div>
";
?>
